name: allowme
description: ideal companionship

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^1.0.11
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  

flutter:
  uses-material-design: true
  assets:
   - assets/

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/icon/ic_launcher_xxxhdpi.png
  image_path_ios: assets/icon/ios.png
  adaptive_icon_background: assets/icon/ic_background.png
  adaptive_icon_foreground: assets/icon/ic_foreground.png